service: nestjsapi-demo

plugins:
  - '@hewmen/serverless-plugin-typescript'
  - serverless-optimizer
  - serverless-offline
  - serverless-plugin-warmup

provider:
  name: aws
  runtime: nodejs18.x

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
