service: nestjsapi-demo # Your service name

plugins:
  - 'serverless-jetpack' # Plugin for handling deployment

provider:
  name: aws
  runtime: nodejs18.x # Node.js runtime version
  region: eu-north-1 # Specify your region here

functions:
  main:
    handler: dist-lambda/lambda.handler # The location of your handler in the dist folder after TypeScript build
    # No API Gateway trigger needed because it's already configured in the AWS Console
    timeout: 30 # Increase to the required time in seconds
    events:
      - http:
          method: GET
          path: / # Base path
      - http:
          method: GET
          path: users/hello # Full path to match the controller

resources:
  # No additional resources are needed since API Gateway is already configured in AWS Console
  Resources: {} # This will ensure no new resources are created by Serverless
